version: '3.9'

services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: posvyat 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
